### ISSUE TITLE
TODO: add the deep water (and land?) masking to NIDEM

### ISSUE THREAD

**Issue by erialC-P** [GeoscienceAustralia/dea-intertidal#2]
Add the deep water masking to NIDEM. 

Did C2 apply a land mask too? (Testing isn't showing a requirement for land masking but for consistency with C2, it might be worth looking into. Due to new tidal modelling, less of the inland estuaries etc are captured in C3 than in C2 so there isn't an obvious requirement for land masking in the new product.)

**Comment by robbibt** [comment]
It did (clipped to 25 m on both sides of 0 m / Mean Sea Level) - relevant bit of the NIDEM paper here:
https://www.sciencedirect.com/science/article/pii/S0272771418308783

![image](https://user-images.githubusercontent.com/17680388/220804441-442dc1d3-dadd-4067-8647-d52882a3efba.png)

Possibly isn't required now that we filter out pixels that don't correlate with tide? Not sure...

**Comment by robbibt** [comment]
Closed by #29
